- name: install apache httpd
  yum:
    name: httpd
    state: latest

- name: enabled http in firewalld
  firewalld:
    permanent: true
    service: http
    state: enabled
    immediate: true

- name: start httpd
  systemd:
    name: httpd
    state: started
    enabled: yes
